- hosts: all
  connection: httpapi
  tasks:
    - name: Get Domain UUID
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain

    - name: Create security zones
      cisco.fmcansible.fmc_configuration:
        operation: createMultipleSecurityZoneObject
        data:
          - name: gcp-inside
            interfaceMode: ROUTED
            type: SecurityZone
          - name: gcp-outside
            interfaceMode: ROUTED
            type: SecurityZone
        path_params:
          domainUUID: '{{ domain[0].uuid }}'
        query_params:
          bulk: true
        register_as: zones