- hosts: all
  connection: httpapi
  tasks:
    - name: Get Domain UUID
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain

    - name: Create gateway host object
      cisco.fmcansible.fmc_configuration:
        operation: createMultipleHostObject
        data:
          - name: gcp-default-gateway
            value: "10.10.2.1"
            type: "hostobject"
          - name: gcp-inside-gateway
            value: "10.10.3.1"
            type: "hostobject"
          - name: gcp-app-lb
            value: "10.10.6.2"
            type: "hostobject"
        path_params:
          domainUUID: '{{ domain[0].uuid }}'
        query_params:
          bulk: true
        register_as: hostobjects

    - name: Create network object 
      cisco.fmcansible.fmc_configuration:
        operation: createMultipleNetworkObject
        data:
          name: "gcp-app"
          value: "10.10.6.0/24"
          type: "networkobject"
        path_params:
          domainUUID: '{{ domain[0].uuid }}'

    
         
