- hosts: all
  connection: httpapi
  tasks:
    - name: Get Domain UUID
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain
    
    - name: Create prefilter policy
      cisco.fmcansible.fmc_configuration:
        operation: "createPrefilterPolicy"
        data:
          type: "PrefilterPolicy"
          name: "PrefilterPolicy1"
          description: "Created by terraform"
        path_params:
          domainUUID: "{{ domain[0].uuid }}"
