- hosts: all
  connection: httpapi
  tasks:
    - name: Get Domain UUID
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain
    

    - name: Get Devices
      cisco.fmcansible.fmc_configuration:
        operation: getAllDevice
        path_params:
          domainUUID: '{{ domain[0].uuid }}' 
        register_as: device_list 

    - name: Get NAT
      cisco.fmcansible.fmc_configuration:
        operation: getAllFTDNatPolicy
        path_params:
          domainUUID: '{{ domain[0].uuid }}' 
          
        register_as: getNAT
    
    - name: Associate NAT
      cisco.fmcansible.fmc_configuration:
        operation: createPolicyAssignment
        data:
          name: assignment
          policy: 
            name: '{{ getNAT[0].name }}'
            type: '{{ getNAT[0].type }}'
            id: '{{ getNAT[0].id }}'
          targets: [ '{{ device_list[0] }}' ]  
        path_params:
          domainUUID: '{{ domain[0].uuid }}'