[all:vars]
ansible_network_os=cisco.fmcansible.fmc

[vfmc]
44.215.40.124 ansible_user=admin ansible_password=Cisco@123 ansible_httpapi_port=443 ansible_httpapi_use_ssl=True ansible_httpapi_validate_certs=False

[vfmc:vars]
network_type=HOST